# Makefile for threadtest1 and threadtest1b

CC = gcc
LIBS = -lpthread

threadtest1: threadtest1.c
	$(CC) threadtest1.c -o threadtest1 $(LIBS)

threadtest1b: threadtest1b.c
	$(CC) threadtest1b.c -o threadtest1b $(LIBS)

clean:
	rm -f threadtest1 threadtest1b
